[project]
name = "agentic-practise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.4.0",
    "langchain-groq>=1.1.3",
    "langgraph>=1.2.11",
    "langgraph-checkpoint-postgres>=3.1.2",
    "langsmith>=0.12.1",
    "psycopg[binary,pool]>=3.3.5",
    "python-dotenv>=1.2.3",
    "tavily-agent-toolkit>=0.1.0",
]

[project.scripts]
agentic-practise = "agentic_practise:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
